# Configuration for YouTube Music Downloader


[paths]
# Main directories
json_dir = "JSON"
cred_dir = "CREDS" 
logs_dir = "LOGS"
config_dir = "CONFIG"

# Download paths and database
download_path = "~/YOUTUBE/MUSICS"
db_path = "music.db"

# Configuration files
client_secrets_file = "client_secret.json"
token_file = "token.json"
playlist_videos_file = "playlist_videos.json"



[patterns]
# Pattern files
unwanted_patterns_file = "unwanted_patterns.txt"
remix_patterns_file = "remix_patterns.txt"
private_patterns_file = "private_patterns.txt" 
trusted_artists_file = "trusted_artists.txt"

[processing]
# Main processing configuration

playlist_id = "LL"  # "LL" = liked videos
max_lyrics_retries = 1

use_sponsorblock = true
get_lyrics = true
get_thumbnail = true
add_tags = true
add_album = true
embed_metadata = true


force_recompute_lyrics = false
force_recompute_thumbnails = false
force_recompute_tags = true
force_recompute_album = true
force_recompute_yt_info = false


thumbnail_format = "pad"  # "pad" or "crop"

sponsorblock_categories = ["music_offtopic", "sponsor", "intro", "outro"]

tag_separator = " ~ "
tag_start_delimiter = "["
tag_end_delimiter = "]"
tag_inner_separator = ","


retry_unavailable = true
retry_private = true

info = true
error = true
test_run = false

clean = false
remove_no_longer_in_playlist = false
remove_malformatted = true
create_db_if_not = true
add_folder_files_not_in_list = true

[logging]
# Logging configuration

console_globally = true
level_console = "WARNING"  # VERBOSE, DEBUG, INFO, WARNING, ERROR, CRITICAL
level_logfiles = "DEBUG"
overlap_fprint = true
overwrite_unchanged = true
