JSON_DIR = "JSON"
CRED_DIR = "CREDS"

CLIENT_SECRETS_FILE = f"{CRED_DIR}/client_secret.json"
TOKEN_FILE = f"{CRED_DIR}/token.json"
LIKED_VIDEOS_FILE = f"{JSON_DIR}/liked_videos.json"
PLAYLIST_VIDEOS_FILE = f"{JSON_DIR}/playlist_videos.json"
PLAYLIST_VIDEOS_INFOS_FILE = f"{JSON_DIR}/playlist_videos_infos.json"
VIDEOS_TO_LIKE_FILE = f"{JSON_DIR}/videos_to_like.json"
VIDEOS_TO_ADD_IN_PLAYLIST_FILE = f"{JSON_DIR}/videos_to_add_in_playlist.json"
VIDEOS_TO_DOWNLOAD_FILE = f"{JSON_DIR}/videos_to_download.json"
VIDEOS_INFOS_FILE = f"{JSON_DIR}/video_infos.json"
ERROR_DOWNLOADED_FILE = f"{JSON_DIR}/error_downloaded.json"
ERROR_LIKED_FILE = f"{JSON_DIR}/error_liked.json"
ERROR_ADDED_FILE = f"{JSON_DIR}/error_added.json"